[v2.9] forwardport use self-hosted runners and registry env (#47322)
* add install yq action

* add go version to setup-build-env

* fix docker image digests dependency and needs

* use self-hosted runners for pull-requests

* update push-release to use registry var and self-hosted runners

diff --git a/.github/actions/setup-build-env/action.yml b/.github/actions/setup-build-env/action.yml
--- a/.github/actions/setup-build-env/action.yml
+++ b/.github/actions/setup-build-env/action.yml
@@ -13,6 +13,9 @@ outputs:
   HELM_VERSION: 
     description: "HELM_VERSION from package/Dockerfile"
     value: ${{ steps.vars.outputs.HELM_VERSION }}
+  GO_VERSION: 
+    description: "GO_VERSION from package/Dockerfile"
+    value: ${{ steps.vars.outputs.GO_VERSION }}
   HELM_UNITTEST_VERSION: 
     description: "HELM_UNITTEST_VERSION from Dockerfile.dapper"
     value: ${{ steps.vars.outputs.HELM_UNITTEST_VERSION }}
@@ -39,6 +42,7 @@ runs:
         CATTLE_K3S_VERSION=$(grep -m1 'ENV CATTLE_K3S_VERSION' package/Dockerfile | awk '{print $3}')
         HELM_VERSION=$(grep -m1 'ENV HELM_VERSION' package/Dockerfile | awk '{print $3}')
         CATTLE_HELM_VERSION=$(grep -m1 'ENV CATTLE_HELM_VERSION' package/Dockerfile | awk '{print $3}')
+        GO_VERSION=$(grep -m1 'golang:' package/Dockerfile | cut -d ':' -f2 | cut -d ' ' -f1)
         HELM_UNITTEST_VERSION=$(grep -m1 'ENV HELM_UNITTEST_VERSION' Dockerfile.dapper | awk '{print $3}')
         RKE_VERSION=$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $2}')
         if [[ -z "$RKE_VERSION" ]]; then
@@ -65,6 +69,10 @@ runs:
           echo "CATTLE_HELM_VERSION not found"
           exit 1
         fi
+        if [[ -z "$GO_VERSION" ]]; then
+          echo "GO_VERSION not found"
+          exit 1
+        fi
         if [[ -z "$HELM_UNITTEST_VERSION" ]]; then
           echo "HELM_UNITTEST_VERSION not found"
           exit 1
@@ -89,6 +97,7 @@ runs:
         echo "CATTLE_K3S_VERSION=$CATTLE_K3S_VERSION" >> $GITHUB_OUTPUT 
         echo "HELM_VERSION=$HELM_VERSION" >> $GITHUB_OUTPUT 
         echo "CATTLE_HELM_VERSION=$CATTLE_HELM_VERSION" >> $GITHUB_OUTPUT 
+        echo "GO_VERSION=$GO_VERSION" >> $GITHUB_OUTPUT 
         echo "HELM_UNITTEST_VERSION=$HELM_UNITTEST_VERSION" >> $GITHUB_OUTPUT
         echo "RKE_VERSION=$RKE_VERSION" >> $GITHUB_OUTPUT 
         echo "CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION" >> $GITHUB_OUTPUT 
