Re-Pin the CAPI chart version
The CAPI chart chart version used to be pinned, but this is no longer the case
since the move to GHA.

Change the workflows to pin the version in the images it produces.

Also add the missing argument for this version in dev-scripts/quick, and pass
it to the rancher process started by local provisioning and integration test
scripts. Doing this will also make the GHA provisioning test to run with the
pinned version, since it uses the script. The GHA integration tests will also
have the version pinned because they use the docker image produced in previous
steps.

diff --git a/.github/actions/setup-build-env/action.yml b/.github/actions/setup-build-env/action.yml
--- a/.github/actions/setup-build-env/action.yml
+++ b/.github/actions/setup-build-env/action.yml
@@ -25,6 +25,9 @@ outputs:
   CATTLE_RANCHER_WEBHOOK_VERSION: 
     description: "CATTLE_RANCHER_WEBHOOK_VERSION from scripts/export-config"
     value: ${{ steps.vars.outputs.CATTLE_RANCHER_WEBHOOK_VERSION }}
+  CATTLE_RANCHER_PROVISIONING_CAPI_VERSION:
+    description: "CATTLE_RANCHER_PROVISIONING_CAPI_VERSION from scripts/export-config"
+    value: ${{ steps.vars.outputs.CATTLE_RANCHER_PROVISIONING_CAPI_VERSION }}
   CATTLE_CSP_ADAPTER_MIN_VERSION: 
     description: "CATTLE_CSP_ADAPTER_MIN_VERSION from scripts/export-config"
     value: ${{ steps.vars.outputs.CATTLE_CSP_ADAPTER_MIN_VERSION }}
@@ -50,6 +53,7 @@ runs:
         fi
         RKE_VERSION=$RKE_VERSION
         CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION
+        CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=$CATTLE_RANCHER_PROVISIONING_CAPI_VERSION
         CATTLE_CSP_ADAPTER_MIN_VERSION=$CATTLE_CSP_ADAPTER_MIN_VERSION
         CATTLE_FLEET_VERSION=$CATTLE_FLEET_VERSION
 
@@ -85,6 +89,10 @@ runs:
           echo "CATTLE_RANCHER_WEBHOOK_VERSION not found"
           exit 1
         fi
+        if [[ -z "$CATTLE_RANCHER_PROVISIONING_CAPI_VERSION" ]]; then
+          echo "CATTLE_RANCHER_PROVISIONING_CAPI_VERSION not found"
+          exit 1
+        fi
         if [[ -z "$CATTLE_CSP_ADAPTER_MIN_VERSION" ]]; then
           echo "CATTLE_CSP_ADAPTER_MIN_VERSION not found"
           exit 1
@@ -101,6 +109,7 @@ runs:
         echo "HELM_UNITTEST_VERSION=$HELM_UNITTEST_VERSION" >> $GITHUB_OUTPUT
         echo "RKE_VERSION=$RKE_VERSION" >> $GITHUB_OUTPUT 
         echo "CATTLE_RANCHER_WEBHOOK_VERSION=$CATTLE_RANCHER_WEBHOOK_VERSION" >> $GITHUB_OUTPUT 
+        echo "CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=$CATTLE_RANCHER_PROVISIONING_CAPI_VERSION" >> $GITHUB_OUTPUT
         echo "CATTLE_CSP_ADAPTER_MIN_VERSION=$CATTLE_CSP_ADAPTER_MIN_VERSION" >> $GITHUB_OUTPUT 
         echo "CATTLE_FLEET_VERSION=$CATTLE_FLEET_VERSION" >> $GITHUB_OUTPUT 
 
