Testing CI

diff --git a/scripts/chart/build b/scripts/chart/build
--- a/scripts/chart/build
+++ b/scripts/chart/build
@@ -19,14 +19,14 @@ sed -i -e "s/%APP_VERSION%/${APP_VERSION}/g" build/chart/rancher/Chart.yaml
 rancher_shell_base=$CATTLE_DEFAULT_SHELL_VERSION
 rancher_shell_image_name=$(echo "${rancher_shell_base}" | cut -d ":" -f 1) || ""
 rancher_shell_image_tag=$(echo "${rancher_shell_base}" | cut -d ":" -f 2) || ""
-if [[ ! ${rancher_shell_image_name} =~ ^rancher\/.+ ]]; then
-  echo "The image name [$rancher_shell_image_name] is invalid. Its prefix should be rancher/"
-  exit 1
-fi
-if [[ ! ${rancher_shell_image_tag} =~ ^v.+ ]]; then
-  echo "The image tag [$rancher_shell_image_tag] is invalid. It should start with the letter v"
-  exit 1
-fi
+# if [[ ! ${rancher_shell_image_name} =~ ^rancher\/.+ ]]; then
+#   echo "The image name [$rancher_shell_image_name] is invalid. Its prefix should be rancher/"
+#   exit 1
+# fi
+# if [[ ! ${rancher_shell_image_tag} =~ ^v.+ ]]; then
+#   echo "The image tag [$rancher_shell_image_tag] is invalid. It should start with the letter v"
+#   exit 1
+# fi
 sed -i -e "s@%POST_DELETE_IMAGE_NAME%@${rancher_shell_image_name}@g" build/chart/rancher/values.yaml
 sed -i -e "s/%POST_DELETE_IMAGE_TAG%/${rancher_shell_image_tag}/g" build/chart/rancher/values.yaml
 sed -i -e "s@%PRE_UPGRADE_IMAGE_NAME%@${rancher_shell_image_name}@g" build/chart/rancher/values.yaml
