Mapping k8s versions in the config.yaml

diff --git a/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local b/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local
--- a/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local
+++ b/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local
@@ -33,6 +33,9 @@ node {
     def qaseRun = "testrun"
     def testRunConfig = "testrunconfig.yaml"
 
+    def config = env.CONFIG
+    def filename = "config.yaml"
+
     // rancher
     def rancherRepo = scm.getUserRemoteConfigs()[0].getUrl()
     if ("${env.REPO}" != "null" && "${env.REPO}" != "") {
@@ -165,47 +168,7 @@ node {
                   }
                 }
                 dir("./rancher/tests/v2/validation") {
-                  def filename = "config.yaml"
-                  def configContents = env.CONFIG
-
-                  def rancherK8sVersions = ""
-
-                  echo "Printing the contents of the directory"
-
-                  sh "ls -l"
-
-                  sh "pwd"
-
-                  echo "Before the start of script."
-
-                  try{
-                      rancherK8sVersions= sh (
-                        script: "./pipeline/scripts/rancher_k8s_version.sh",
-                        returnStdout: true
-                      )
-                    } catch(err){
-                     echo "Unable to get the versions of rancher and k8s " + err
-                    }
-
-                  // Parse the output
-                  def lines = rancherK8sVersions.split('\n')
-                  def rancherVersion = lines[0].replace("Latest Rancher Version: ", "").trim()
-                  def k8sVersions = lines[1].replace("Latest Kubernetes Versions: ", "").trim()
-
-                  def versionArray = k8sVersions.split(',')
-                  def preUpgradeK8s = versionArray[0]?.trim() 
-                  def postUpgradeK8s = versionArray[1]?.trim() 
-
-                  echo "Rancher Version: ${rancherVersion}"
-                  echo "Kubernetes Versions: ${k8sVersions}"
-
-                  sh "./yq e '.corralConfigs.corralConfigVars.rancher_image_tag = \"${rancherVersion}\"' -i ${configPath}"
-                  sh "./yq e '.corralConfigs.corralConfigVars.rancher_version = \"${rancherVersion}\"' -i ${configPath}"
-                  sh "./yq e '.corralConfigs.corralConfigVars.kubernetes_version = \"${preUpgradeK8s}\"' -i ${configPath}"
-                  sh "./yq e '.rancher.host = \"${rancherHostName}\"' -i ${configPath}"
-
                   writeFile file: filename, text: configContents
-                  env.CATTLE_TEST_CONFIG = workPath+filename
                 }
 
                 dir ("./") {
@@ -217,6 +180,58 @@ node {
               stage('Setup') {
                 sh returnStdout: true, script: 'wget -qO ./yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64'
                 sh returnStdout:true, script: 'chmod a+x ./yq'
+
+                def initConfigPath = "./rancher/tests/v2/validation/config.yaml"
+                scriptPath = "./rancher/tests/v2/validation/pipeline/scripts/rancher_k8s_version.sh"
+
+                def rancherK8sVersions = ""
+                try {
+                  rancherK8sVersions = sh(
+                    script: """
+                      if [ -f ${scriptPath} ]; then
+                      chmod +x ${scriptPath}
+                      ${scriptPath}
+                      else
+                        echo "Script not found!"
+                        exit 1
+                    fi
+                    """,
+                    returnStdout: true
+                  ).trim()
+
+                  def lines = []
+                  if (rancherK8sVersions != "") {
+                    lines = rancherK8sVersions.split('\n')
+                  }
+
+                  if (lines.size() >= 8) {
+                    def rancherVersion = lines[0].replace("Latest Rancher Version: ", "").trim()
+                    def preUpgradeRKE2K8s = lines[2]?.trim()
+                    def postUpgradeRKE2K8s = lines[3]?.trim()
+                    def preUpgradeK3sK8s = lines[4]?.trim()
+                    def postUpgradeK3sK8s = lines[5]?.trim()
+                    def preUpgradeRKE1K8s = lines[6]?.trim()
+                    def postUpgradeRKE1K8s = lines[7]?.trim()
+
+                    sh "./yq e '.corralConfigs.corralConfigVars.rancher_image_tag = \"${rancherVersion}\"' -i ${initConfigPath}"
+                    sh "./yq e '.corralConfigs.corralConfigVars.rancher_version = \"${rancherVersion}\"' -i ${initConfigPath}"
+                    sh "./yq e '.corralConfigs.corralConfigVars.kubernetes_version = \"${preUpgradeRKE2K8s}\"' -i ${initConfigPath}"
+                    sh "./yq e '.clusters.local.kubernetesVersionToUpgrade = \"${postUpgradeRKE2K8s}\"' -i ${initConfigPath}"
+                    sh "./yq e '.clusters.rke2.custom[0].kubernetesVersion = \"${preUpgradeRKE2K8s}\"' -i ${initConfigPath}"
+                    sh "./yq e '.clusters.rke2.custom[0].kubernetesVersionToUpgrade = \"${postUpgradeRKE2K8s}\"' -i ${initConfigPath}"
+                    sh "./yq e '.clusters.k3s.nodeProvider[0].kubernetesVersionToUpgrade = \"${preUpgradeK3sK8s}\"' -i ${initConfigPath}"
+                    sh "./yq e '.clusters.k3s.nodeProvider[0].kubernetesVersionToUpgrade = \"${postUpgradeK3sK8s}\"' -i ${initConfigPath}"
+                    sh "./yq e '.clusters.rke1.nodeProvider[0].kubernetesVersionToUpgrade = \"${preUpgradeRKE1K8s}\"' -i ${initConfigPath}"
+                    sh "./yq e '.clusters.rke1.nodeProvider[0].kubernetesVersionToUpgrade = \"${postUpgradeRKE1K8s}\"' -i ${initConfigPath}"
+
+                } catch (err) {
+                  echo "Unable to get the versions of Rancher and Kubernetes: ${err}"
+                }
+
+                env.CATTLE_TEST_CONFIG = workPath + filename
+
+                echo "CATTLE_TEST_CONFIG: ${env.CATTLE_TEST_CONFIG}"
+
               }
               stage("Build Environment") {
                 try {
