Getting the k8s versions based on rancher version
debug

Updated the rancher versions script to work for community versions

diff --git a/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local b/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local
--- a/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local
+++ b/tests/v2/validation/pipeline/Jenkinsfile.release.upgrade.local
@@ -13,6 +13,7 @@ node {
     def buildTestContainer = "${job_name}${env.BUILD_NUMBER}-buildtest"
     def configGeneratorContainer = "${job_name}${env.BUILD_NUMBER}_generator"
     def cleanupTestContainer = "${job_name}${env.BUILD_NUMBER}_cleanup"
+    def setupContainer = "${job_name}${env.BUILD_NUMBER}-buildtest"
 
     def validationVolume = "ValidationSharedVolume-${job_name}${env.BUILD_NUMBER}"
 
@@ -32,6 +33,7 @@ node {
     def rancherConfig = "rancher_env.config"
     def qaseRun = "testrun"
     def testRunConfig = "testrunconfig.yaml"
+    def testRancherVersions = "testrancherk8s.yaml"
 
     def config = env.CONFIG
     def filename = "config.yaml"
@@ -174,51 +176,87 @@ node {
                   }
                 }
 
-                scriptPath = "./rancher/tests/v2/validation/pipeline/scripts/rancher_k8s_version.sh"
-                
-                def rancherK8sVersions = ""
-                try {
-                  rancherK8sVersions = sh(
-                    script: """
-                      if [ -f ${scriptPath} ]; then
-                      chmod +x ${scriptPath}
-                      ${scriptPath}
-                      else
-                        echo "Script not found!"
-                        exit 1
-                    fi
-                    """,
-                    returnStdout: true
-                  ).trim()
+                try{
+                  sh "docker build . -f ./rancher/tests/v2/validation/Dockerfile.e2e --build-arg CORRAL_VERSION=${env.CORRAL_VERSION} --build-arg RKE_VERSION=${env.RKE_VERSION} -t ${imageName}"
+                  
+                  sh "docker volume create --name ${validationVolume}"
 
-                  def lines = []
-                  if (rancherK8sVersions != "") {
-                    lines = rancherK8sVersions.split('\n')
+                  sh "docker run -v ${validationVolume}:/root  --name ${setupContainer} -t " +
+                  "${imageName} sh -c \"${workPath}pipeline/scripts/rancher_k8s_version.sh\""
+
+                  sh "docker cp ${setupContainer}:/root/go/src/github.com/rancher/rancher/testrancherk8s.yaml ./"
+
+                  if (sh(script: "test -s ./${testRancherVersions} && echo 'not_empty' || echo 'empty'", returnStdout: true).trim() == "empty") {
+                      error "ERROR: (${testRancherVersions}) is empty or missing!"
                   }
+                  
+                 def rancherRKE2Version = sh(
+                      script: "grep -E '^rancherRKE2Version:' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher RKE2 version ${rancherRKE2Version}"
 
-                  if (lines.size() >= 8) {
-                    def rancherImageTag = lines[0].replace("Latest Rancher Version: ", "").trim()
-                    def rancherVersion = rancherImageTag.replace("v", "")
-                    def preUpgradeRKE2K8s = lines[2]?.trim()
-                    def postUpgradeRKE2K8s = lines[3]?.trim()
-                    def preUpgradeK3sK8s = lines[4]?.trim()
-                    def postUpgradeK3sK8s = lines[5]?.trim()
-                    def preUpgradeRKE1K8s = lines[6]?.trim()
-                    def postUpgradeRKE1K8s = lines[7]?.trim()
+
+                  def rancherRKE2VersionToUpgrade = sh(
+                      script: "grep 'rancherRKE2VersionToUpgrade' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher RKE2 version to upgrade ${rancherRKE2VersionToUpgrade}"
+                  
+                  def rancherK3sVersion = sh(
+                      script: "grep -E '^rancherK3sVersion:' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher K3s version ${rancherK3sVersion}"
+                  
+                  def rancherK3sVersionToUpgrade = sh(
+                      script: "grep 'rancherK3sVersionToUpgrade' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher K3s version to upgrade ${rancherK3sVersionToUpgrade}"
+                  
+                  def rancherRKEVersion = sh(
+                      script: "grep -E '^rancherRKEVersion:' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher RKE version ${rancherRKEVersion}"
+                  
+                  def rancherRKEVersionToUpgrade = sh(
+                      script: "grep 'rancherRKEVersionToUpgrade' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher RKE version to upgrade ${rancherRKEVersionToUpgrade}"
+                  
+                  def rancherVersion = sh(
+                      script: "grep 'rancherVersion' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher rancher version ${rancherVersion}"
+                  
+                  def rancherImageTag = sh(
+                      script: "grep 'rancherImageTag' ./${testRancherVersions} | awk '{print \$2}'",
+                      returnStdout: true
+                    ).trim()
+                  println "Rancher rancher image tag version ${rancherImageTag}"
 
                     config = config.replace('${RANCHER_VERSION}', rancherVersion)
                     config = config.replace('${RANCHER_IMAGE_TAG}', rancherImageTag)
-                    config = config.replace('${RANCHER_RKE2_VERSION}', preUpgradeRKE2K8s)
-                    config = config.replace('${RANCHER_RKE2_VERSION_TO_UPGRADE}', postUpgradeRKE2K8s)
-                    config = config.replace('${RANCHER_K3S_VERSION}', preUpgradeK3sK8s)
-                    config = config.replace('${RANCHER_K3S_VERSION_TO_UPGRADE}', postUpgradeK3sK8s)
-                    config = config.replace('${RANCHER_RKE1_VERSION}', preUpgradeRKE1K8s)
-                    config = config.replace('${RANCHER_RKE1_VERSION_TO_UPGRADE}', postUpgradeRKE1K8s)
-                  }
+                    config = config.replace('${RANCHER_RKE2_VERSION}', rancherRKE2Version)
+                    config = config.replace('${RANCHER_RKE2_VERSION_TO_UPGRADE}', rancherRKE2VersionToUpgrade)
+                    config = config.replace('${RANCHER_K3S_VERSION}', rancherK3sVersion)
+                    config = config.replace('${RANCHER_K3S_VERSION_TO_UPGRADE}', rancherK3sVersionToUpgrade)
+                    config = config.replace('${RANCHER_RKE1_VERSION}', rancherVersion)
+                    config = config.replace('${RANCHER_RKE1_VERSION_TO_UPGRADE}', rancherRKEVersionToUpgrade)
                 } catch (err) {
                   echo "Unable to get the versions of Rancher and Kubernetes: ${err}"
                   error "Rancher and k8s versions cannot be retrieved."
+                  sh "docker stop ${setupContainer}"
+                  sh "docker rm -v ${setupContainer}"
+                  sh "docker volume rm -f ${validationVolume}"
                 }
+                sh "docker stop ${setupContainer}"
+                sh "docker rm -v ${setupContainer}"
+                sh "docker volume rm -f ${validationVolume}"
                 
                 dir("./rancher/tests/v2/validation") {
                   writeFile file: filename, text: config
