tfp jenkins file for airgap setups

diff --git a/tests/v2/validation/pipeline/Jenkinsfile.airgap.setup b/tests/v2/validation/pipeline/Jenkinsfile.airgap.setup
--- a/tests/v2/validation/pipeline/Jenkinsfile.airgap.setup
+++ b/tests/v2/validation/pipeline/Jenkinsfile.airgap.setup
@@ -34,40 +34,93 @@ node {
                     string(credentialsId: 'AWS_SSH_PEM_KEY', variable: 'AWS_SSH_PEM_KEY'),
                     string(credentialsId: 'AWS_SSH_KEY_NAME', variable: 'AWS_SSH_KEY_NAME'),
                     string(credentialsId: 'QASE_AUTOMATION_TOKEN', variable: 'QASE_AUTOMATION_TOKEN')]) {
-  stage('Checkout') {
-          deleteDir()
-          checkout([
-                    $class: 'GitSCM',
-                    branches: [[name: "*/${branch}"]],
-                    extensions: scm.extensions + [[$class: 'CleanCheckout']],
-                    userRemoteConfigs: repo
-                  ])
+      stage('Checkout') {
+              deleteDir()
+              checkout([
+                        $class: 'GitSCM',
+                        branches: [[name: "*/${branch}"]],
+                        extensions: scm.extensions + [[$class: 'CleanCheckout']],
+                        userRemoteConfigs: repo
+                      ])
+            }
+        stage('Configure and Build') {
+          config = config.replace('${AWS_SECRET_ACCESS_KEY}', env.AWS_SECRET_ACCESS_KEY)
+          config = config.replace('${AWS_ACCESS_KEY_ID}', env.AWS_ACCESS_KEY_ID)
+
+          writeFile file: 'config.yml', text: config
+
+          def decoded = new String(env.AWS_SSH_PEM_KEY.decodeBase64())
+          writeFile file: 'key.pem', text: decoded
+          
+          env.CATTLE_TEST_CONFIG=rootPath+'config.yml'
+
+          sh "./configure.sh"
+          sh "./build.sh"
         }
-    stage('Configure and Build') {
-      config = config.replace('${AWS_SECRET_ACCESS_KEY}', env.AWS_SECRET_ACCESS_KEY)
-      config = config.replace('${AWS_ACCESS_KEY_ID}', env.AWS_ACCESS_KEY_ID)
-      config = config.replace('${RANCHER_LINODE_ACCESSKEY}', env.RANCHER_LINODE_ACCESSKEY)
+        if  (!(env.HA_CLEANUP.toBoolean())) {
+          stage('Run Module Test') {
+            try {
+              sh """
+                docker run --name ${testContainer} -t -v ${homePath}key.pem:${rootPath}key.pem --env-file ${envFile} ${imageName} sh -c "
+                /root/go/bin/gotestsum --format standard-verbose --packages=${testsDir} --junitfile ${testResultsOut} --jsonfile ${testResultsJSON} -- -timeout=${timeout} -v ${params.TEST_CASE};
+                if [ -f ${rootPath}reporter ]; then ${rootPath}reporter; fi"
+              """
+            } catch(err) {
+                echo 'Test run had failures. Collecting results...'
+            }
+          }
+          stage('Upload tf files to S3 bucket'){
+            try{
+                sh "docker cp ${testContainer}:/root/ ./"
+                sh "ls -lR"
+                script {
+                  sh """
+                      if ls $TERRAFORM_DIR/. 1> /dev/null 2>&1; then
+                          echo "Terraform files found, starting upload."
+                      else
+                          echo "No Terraform files found!"
+                          exit 1
+                      fi
+                        docker run --rm \
+                          -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+                          -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+                          -e AWS_DEFAULT_REGION=$AWS_REGION \
+                          -v $TERRAFORM_DIR/:/root/terraform/ \
+                          amazon/aws-cli \
+                          s3 cp /root/terraform/. s3://$AWS_S3_BUCKET/terraform/ --recursive
+                      """
+                  }
+              }catch(err){
+                  echo "Unable to get the output: ${err}"
+                }
+           }
+        }else{
+          stage('Cleanup setup'){
+              script {
+                sh """
+                    docker run --rm \
+                    -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+                    -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+                    -e AWS_DEFAULT_REGION=$AWS_REGION \
+                    amazon/aws-cli \
+                    s3 cp s3://$AWS_S3_BUCKET/terraform/ /root/terraform/. --recursive
+                  """ 
+                sh """
+                  docker run --rm \
+                  -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+                  -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+                  -e AWS_DEFAULT_REGION=$AWS_REGION \
+                  amazon/aws-cli \
+                  s3 rm s3://$AWS_S3_BUCKET/terraform/ --recursive
+                 """   
+                sh """             
+                  cd /root/terraform
+                  terraform init
+                  terraform destroy
+                """
 
-      writeFile file: 'config.yml', text: config
-
-      def decoded = new String(env.AWS_SSH_PEM_KEY.decodeBase64())
-      writeFile file: 'key.pem', text: decoded
-      
-      env.CATTLE_TEST_CONFIG=rootPath+'config.yml'
-
-      sh "./configure.sh"
-      sh "./build.sh"
+              }
+           }
+        }
     }
-    stage('Run Module Test') {
-      try {
-        sh """
-          docker run --name ${testContainer} -t -v ${homePath}key.pem:${rootPath}key.pem --env-file ${envFile} ${imageName} sh -c "
-          /root/go/bin/gotestsum --format standard-verbose --packages=${testsDir} --junitfile ${testResultsOut} --jsonfile ${testResultsJSON} -- -timeout=${timeout} -v ${params.TEST_CASE};
-          if [ -f ${rootPath}reporter ]; then ${rootPath}reporter; fi"
-        """
-      } catch(err) {
-          echo 'Test run had failures. Collecting results...'
-      }
-    }
-  }
 }
