simply use a bigger disk

diff --git a/scripts/provisioning-tests b/scripts/provisioning-tests
--- a/scripts/provisioning-tests
+++ b/scripts/provisioning-tests
@@ -193,13 +193,13 @@ touch /tmp/rancher.log
 
 # Try and use RAM as the storage for k3s etcd to speed up provisioning tests.
 # If the mount fails, fall back to disk.
-ETCD_DIR=/var/lib/rancher/k3s/server/db
-if ! mountpoint -q "$ETCD_DIR"; then
-  mkdir -p "$ETCD_DIR"
-  mount -t tmpfs -o size=${V2PROV_ETCD_TMPFS_SIZE:-2g} tmpfs "$ETCD_DIR" \
-    && echo "Mounted tmpfs over $ETCD_DIR" \
-    || echo "WARNING: tmpfs mount failed; k3s etcd using disk"
-fi
+#ETCD_DIR=/var/lib/rancher/k3s/server/db
+#if ! mountpoint -q "$ETCD_DIR"; then
+#  mkdir -p "$ETCD_DIR"
+#  mount -t tmpfs -o size=${V2PROV_ETCD_TMPFS_SIZE:-2g} tmpfs "$ETCD_DIR" \
+#    && echo "Mounted tmpfs over $ETCD_DIR" \
+#    || echo "WARNING: tmpfs mount failed; k3s etcd using disk"
+#fi
 
 mkdir -p /var/lib/rancher/$DIST/agent/images
 grep PodTestImage ./tests/v2prov/defaults/defaults.go | cut -f2 -d'"' > /var/lib/rancher/$DIST/agent/images/pull.txt
