fix linkflags

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -15,163 +15,163 @@ env:
   HELM_UNITTEST_VERSION: 0.3.2
   HELM_URL_V3: https://get.helm.sh/helm-v3.13.3-linux-amd64.tar.gz
 jobs:
-  validate:
-    runs-on: ubuntu-latest
-    container:
-      image: registry.suse.com/bci/golang:1.21
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Install Dependencies
-        run: |
-          zypper -n install gawk python311-pip python311-base python311 python311-devel python311-tox libffi-devel libopenssl-devel
-          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2; \
-      - name: Validate
-        run: ./scripts/validate
-  build-chart:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Install dependencies
-        run: |
-          sudo snap install yq
-          curl ${{ env.HELM_URL_V3 }} | tar xvzf - --strip-components=1 -C /tmp/ && \
-          sudo mv /tmp/helm /usr/bin/helm_v3 && \
-          sudo chmod +x /usr/bin/helm_v3
-          helm_v3 plugin install https://github.com/helm-unittest/helm-unittest.git --version ${{ env.HELM_UNITTEST_VERSION }}; \
-      - name: Build
-        run: ./scripts/chart/build chart
-      - name: Validate
-        run: ./scripts/chart/validate
-      - name: Test
-        run: ./scripts/chart/test
-      - name: Package
-        run: ./scripts/chart/package
-  build-server:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        os: [linux]
-        arch: [amd64, arm64]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Setup Environment Variables
-        run: |
-          echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
-          echo "RKE_VERSION=$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.IMAGE }}
-          flavor: |
-            latest=false
-      - name: Docker Registry Login
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Create k3s images file
-        run: touch k3s-airgap-images.tar
-      - name: Download data.json
-        run: curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ env.CATTLE_KDM_BRANCH }}/data.json > ./data.json
-      - name: Build and export server
-        id: build
-        uses: docker/build-push-action@v5
-        with:
-          push: false
-          build-args: |
-            "VERSION=${{ env.COMMIT }}"
-            "COMMIT=${{ env.COMMIT }}"
-            "RKE_VERSION=${{ env.RKE_VERSION }}"
-            "ARCH=${{ matrix.arch }}"
-          tags: ${{ env.IMAGE }}:${{ env.TAG }}-${{ matrix.arch }}
-          context: .
-          platforms: "${{ matrix.os }}/${{ matrix.arch }}"
-          file: ./package/Dockerfile
-          labels: "${{ steps.meta.outputs.labels }}"
-          outputs: type=docker,dest=/tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
-      - name: Upload image
-        uses: actions/upload-artifact@v4
-        with:
-          name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
-          path: /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
-          if-no-files-found: error
-          retention-days: 1
-          overwrite: false
-  build-agent:
-    needs: [build-server]
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        os: [linux]
-        arch: [amd64, arm64]
-    services:
-      registry:
-        image: registry:2
-        ports:
-          - 5000:5000
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Setup Environment Variables
-        run: |
-          echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ env.IMAGE }}
-          flavor: |
-            latest=false
-      - name: Docker Registry Login
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-        with:
-          driver-opts: network=host
-      - name: Download rancher image
-        uses: actions/download-artifact@v4
-        with:
-          name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
-          path: /tmp
-      - name: Load image
-        run: |
-          image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
-          if [ -z "$image_id" ]; then
-            echo "Error: Failed to load image from tarball!"
-            exit 1
-          fi
-          docker tag "$image_id" localhost:5000/${{ env.IMAGE }}:${{ env.TAG }}
-          docker push localhost:5000/${{ env.IMAGE }}:${{ env.TAG }}
-          docker image ls -a  
-      - name: Build agent
-        id: build
-        uses: docker/build-push-action@v5
-        with:
-          push:  ${{ github.event_name != 'pull_request' }}
-          build-args: |
-            "VERSION=${{ env.COMMIT }}"
-            "ARCH=${{ matrix.arch }}"
-            "RANCHER_TAG=${{ env.TAG }}"
-            "RANCHER_REPO=${{ env.REPOSITORY_OWNER }}"
-            "REGISTRY=localhost:5000"
-          tags: ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-${{ matrix.arch }}
-          context: .
-          platforms: "${{ matrix.os }}/${{ matrix.arch }}"
-          file: ./package/Dockerfile.agent
-          labels: "${{ steps.meta.outputs.labels }}"
+  # validate:
+  #   runs-on: ubuntu-latest
+  #   container:
+  #     image: registry.suse.com/bci/golang:1.21
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Install Dependencies
+  #       run: |
+  #         zypper -n install gawk python311-pip python311-base python311 python311-devel python311-tox libffi-devel libopenssl-devel
+  #         curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2; \
+  #     - name: Validate
+  #       run: ./scripts/validate
+  # build-chart:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Install dependencies
+  #       run: |
+  #         sudo snap install yq
+  #         curl ${{ env.HELM_URL_V3 }} | tar xvzf - --strip-components=1 -C /tmp/ && \
+  #         sudo mv /tmp/helm /usr/bin/helm_v3 && \
+  #         sudo chmod +x /usr/bin/helm_v3
+  #         helm_v3 plugin install https://github.com/helm-unittest/helm-unittest.git --version ${{ env.HELM_UNITTEST_VERSION }}; \
+  #     - name: Build
+  #       run: ./scripts/chart/build chart
+  #     - name: Validate
+  #       run: ./scripts/chart/validate
+  #     - name: Test
+  #       run: ./scripts/chart/test
+  #     - name: Package
+  #       run: ./scripts/chart/package
+  # build-server:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       os: [linux]
+  #       arch: [amd64, arm64]
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Setup Environment Variables
+  #       run: |
+  #         echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
+  #         echo "RKE_VERSION=$(grep -m1 'github.com/rancher/rke' go.mod | awk '{print $2}')" >> "$GITHUB_ENV"
+  #     - name: Docker meta
+  #       id: meta
+  #       uses: docker/metadata-action@v5
+  #       with:
+  #         images: ${{ env.IMAGE }}
+  #         flavor: |
+  #           latest=false
+  #     - name: Docker Registry Login
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PASSWORD }}
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #     - name: Create k3s images file
+  #       run: touch k3s-airgap-images.tar
+  #     - name: Download data.json
+  #       run: curl -sLf https://releases.rancher.com/kontainer-driver-metadata/${{ env.CATTLE_KDM_BRANCH }}/data.json > ./data.json
+  #     - name: Build and export server
+  #       id: build
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         push: false
+  #         build-args: |
+  #           "VERSION=${{ env.COMMIT }}"
+  #           "COMMIT=${{ env.COMMIT }}"
+  #           "RKE_VERSION=${{ env.RKE_VERSION }}"
+  #           "ARCH=${{ matrix.arch }}"
+  #         tags: ${{ env.IMAGE }}:${{ env.TAG }}-${{ matrix.arch }}
+  #         context: .
+  #         platforms: "${{ matrix.os }}/${{ matrix.arch }}"
+  #         file: ./package/Dockerfile
+  #         labels: "${{ steps.meta.outputs.labels }}"
+  #         outputs: type=docker,dest=/tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
+  #     - name: Upload image
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
+  #         path: /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
+  #         if-no-files-found: error
+  #         retention-days: 1
+  #         overwrite: false
+  # build-agent:
+  #   needs: [build-server]
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       os: [linux]
+  #       arch: [amd64, arm64]
+  #   services:
+  #     registry:
+  #       image: registry:2
+  #       ports:
+  #         - 5000:5000
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #     - name: Setup Environment Variables
+  #       run: |
+  #         echo "ARCH=${{ matrix.arch }}" >> "$GITHUB_ENV"
+  #     - name: Docker meta
+  #       id: meta
+  #       uses: docker/metadata-action@v5
+  #       with:
+  #         images: ${{ env.IMAGE }}
+  #         flavor: |
+  #           latest=false
+  #     - name: Docker Registry Login
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ secrets.DOCKER_USERNAME }}
+  #         password: ${{ secrets.DOCKER_PASSWORD }}
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #       with:
+  #         driver-opts: network=host
+  #     - name: Download rancher image
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
+  #         path: /tmp
+  #     - name: Load image
+  #       run: |
+  #         image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
+  #         if [ -z "$image_id" ]; then
+  #           echo "Error: Failed to load image from tarball!"
+  #           exit 1
+  #         fi
+  #         docker tag "$image_id" localhost:5000/${{ env.IMAGE }}:${{ env.TAG }}
+  #         docker push localhost:5000/${{ env.IMAGE }}:${{ env.TAG }}
+  #         docker image ls -a  
+  #     - name: Build agent
+  #       id: build
+  #       uses: docker/build-push-action@v5
+  #       with:
+  #         push:  ${{ github.event_name != 'pull_request' }}
+  #         build-args: |
+  #           "VERSION=${{ env.COMMIT }}"
+  #           "ARCH=${{ matrix.arch }}"
+  #           "RANCHER_TAG=${{ env.TAG }}"
+  #           "RANCHER_REPO=${{ env.REPOSITORY_OWNER }}"
+  #           "REGISTRY=localhost:5000"
+  #         tags: ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-${{ matrix.arch }}
+  #         context: .
+  #         platforms: "${{ matrix.os }}/${{ matrix.arch }}"
+  #         file: ./package/Dockerfile.agent
+  #         labels: "${{ steps.meta.outputs.labels }}"
   build-agent-windows:
     runs-on: windows-2019
     steps:
