integration tests on push release

diff --git a/.github/workflows/push-release.yml b/.github/workflows/push-release.yml
--- a/.github/workflows/push-release.yml
+++ b/.github/workflows/push-release.yml
@@ -86,6 +86,12 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+      - name: Clean runner
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
       - name: Setup Environment Variables
         uses: ./.github/actions/setup-tag-env
       - name: Setup RKE_VERSION env
@@ -99,12 +105,6 @@ jobs:
           images: ${{ env.IMAGE }}
           flavor: |
             latest=false
-      - name: Load Secrets from Vault
-        uses: rancher-eio/read-vault-secrets@main
-        with:
-          secrets: |
-            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
-            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
       - name: Docker Registry Login
         uses: docker/login-action@v3
         with:
@@ -122,7 +122,7 @@ jobs:
         id: build
         uses: docker/build-push-action@v5
         with:
-          push: true
+          push: false
           build-args: |
             "VERSION=${{ env.TAG }}"
             "COMMIT=${{ env.COMMIT }}"
@@ -133,55 +133,27 @@ jobs:
           platforms: "${{ matrix.os }}/${{ matrix.arch }}"
           file: ./package/Dockerfile
           labels: "${{ steps.meta.outputs.labels }}"
-  merge-server-manifest:
-    runs-on: ubuntu-latest
-    needs: [build-server]
-    permissions:
-      contents: read
-      id-token: write
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-      - name: Setup Environment Variables
-        uses: ./.github/actions/setup-tag-env
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
+          outputs: type=docker,dest=/tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
+      - name: Upload image
+        uses: actions/upload-artifact@v4
         with:
-          images: ${{ env.IMAGE }}
-          flavor: |
-            latest=false
-      - name: Load Secrets from Vault
-        uses: rancher-eio/read-vault-secrets@main
-        with:
-          secrets: |
-            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
-            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ env.DOCKER_USERNAME }}
-          password: ${{ env.DOCKER_PASSWORD }}
-      - name: Create manifest list and push
-        run: |
-          docker buildx imagetools create -t ${{ env.IMAGE }}:${{ env.TAG }} ${{ env.IMAGE }}:${{ env.TAG }}-amd64 ${{ env.IMAGE }}:${{ env.TAG }}-arm64
-      - name: Create head manifest list and push
-        run: |
-          if [[ "${{ github.ref_name }}" == release/v* ]]; then
-            docker buildx imagetools create -t ${{ env.IMAGE }}:${{ env.HEAD_TAG }} ${{ env.IMAGE }}:${{ env.TAG }}-amd64 ${{ env.IMAGE }}:${{ env.TAG }}-arm64
-          fi
-      - name: Inspect image
-        run: |
-          docker buildx imagetools inspect ${{ env.IMAGE }}:${{ env.TAG }}
+          name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
+          path: /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar
+          if-no-files-found: error
+          retention-days: 1
+          overwrite: false
   build-agent:
-    needs: [merge-server-manifest]
+    needs: [build-server]
     runs-on: ubuntu-latest
     strategy:
       matrix:
         os: [linux]
         arch: [amd64, arm64]
+    services:
+      registry:
+        image: registry:2
+        ports:
+          - 5000:5000
     permissions:
       contents: read
       id-token: write
@@ -190,6 +162,26 @@ jobs:
         uses: actions/checkout@v4
       - name: Setup Environment Variables
         uses: ./.github/actions/setup-tag-env
+      - name: Clean runner
+        run: |
+          sudo rm -rf /usr/share/dotnet
+          sudo rm -rf /opt/ghc
+          sudo rm -rf "/usr/local/share/boost"
+          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+      - name: Download rancher image
+        uses: actions/download-artifact@v4
+        with:
+          name: "rancher-${{ matrix.os }}-${{ matrix.arch }}"
+          path: /tmp
+      - name: Load image
+        run: |
+          image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
+          if [ -z "$image_id" ]; then
+            echo "Error: Failed to load image from tarball!"
+            exit 1
+          fi
+          docker tag "$image_id" localhost:5000/${{ env.IMAGE }}:${{ env.TAG }}
+          docker push localhost:5000/${{ env.IMAGE }}:${{ env.TAG }}
       - name: Docker meta
         id: meta
         uses: docker/metadata-action@v5
@@ -197,12 +189,6 @@ jobs:
           images: ${{ env.IMAGE }}
           flavor: |
             latest=false
-      - name: Load Secrets from Vault
-        uses: rancher-eio/read-vault-secrets@main
-        with:
-          secrets: |
-            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
-            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
       - name: Docker Registry Login
         uses: docker/login-action@v3
         with:
@@ -216,18 +202,34 @@ jobs:
         id: build
         uses: docker/build-push-action@v5
         with:
-          push: true
+          push: false
           build-args: |
             "VERSION=${{ env.COMMIT }}"
             "ARCH=${{ matrix.arch }}"
             "RANCHER_TAG=${{ env.TAG }}"
             "RANCHER_REPO=${{ env.REPOSITORY_OWNER }}"
+            "REGISTRY=localhost:5000"
           tags: ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-${{ matrix.arch }}
           context: .
           platforms: "${{ matrix.os }}/${{ matrix.arch }}"
           file: ./package/Dockerfile.agent
           labels: "${{ steps.meta.outputs.labels }}"
+          outputs: type=docker,dest=/tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
+      - name: Upload image
+        uses: actions/upload-artifact@v4
+        with:
+          name: "rancher-agent-${{ matrix.os }}-${{ matrix.arch }}"
+          path: /tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar
+          if-no-files-found: error
+          retention-days: 1
+          overwrite: false
+  integration-tests:
+    needs: [build-agent]
+    uses: ./.github/workflows/integration-tests.yml
+    with:
+      parent_run_id: ${{ github.run_id }}
   build-agent-windows:
+    needs: [integration-tests]
     strategy:
       matrix:
         os: [windows]
@@ -257,9 +259,52 @@ jobs:
           docker build -t ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-windows-${{ matrix.version }} --build-arg VERSION=${{ env.TAG }} --build-arg SERVERCORE_VERSION=ltsc${{ matrix.version }} -f package/windows/Dockerfile.agent .
           docker push ${{ env.IMAGE_AGENT }}:${{ env.TAG }}-windows-${{ matrix.version }}
         shell: bash
-  merge-agent-manifest:
+  push-images:
     runs-on: ubuntu-latest
-    needs: [build-agent, build-agent-windows]
+    needs: [integration-tests]
+    permissions:
+      contents: read
+      id-token: write
+    strategy:
+      matrix:
+        os: [linux]
+        arch: [amd64, arm64]
+    steps:
+      - name: Download rancher image
+        uses: actions/download-artifact@v4
+        with:
+          pattern: "*-${{ matrix.os }}-${{ matrix.arch }}.tar"
+          path: /tmp
+          merge-multiple: true
+      - name: Setup Environment Variables
+        uses: ./.github/actions/setup-tag-env
+      - name: Load Secrets from Vault
+        uses: rancher-eio/read-vault-secrets@main
+        with:
+          secrets: |
+            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
+            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
+      - name: Push server image
+        run: |
+          image_id=$(docker load --input /tmp/rancher-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
+          if [ -z "$image_id" ]; then
+            echo "Error: Failed to load image from tarball!"
+            exit 1
+          fi
+          docker tag "$image_id" docker.io/${{ env.IMAGE }}:${{ env.TAG }}
+          docker push docker.io/${{ env.IMAGE }}:${{ env.TAG }}
+      - name: Push agent image
+        run: |
+          image_agent_id=$(docker load --input /tmp/rancher-agent-${{ matrix.os }}-${{ matrix.arch }}.tar 2>&1 | grep "Loaded image" | awk '{print $NF}')
+          if [ -z "$image_agent_id" ]; then
+            echo "Error: Failed to load image from tarball!"
+            exit 1
+          fi
+          docker tag "$image_agent_id" docker.io/${{ env.IMAGE_AGENT }}:${{ env.TAG }}
+          docker push docker.io/${{ env.IMAGE_AGENT }}:${{ env.TAG }}
+  merge-server-manifest:
+    runs-on: ubuntu-latest
+    needs: [push-images]
     permissions:
       contents: read
       id-token: write
@@ -270,13 +315,41 @@ jobs:
         uses: ./.github/actions/setup-tag-env
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
+      - name: Load Secrets from Vault
+        uses: rancher-eio/read-vault-secrets@main
         with:
-          images: ${{ env.IMAGE_AGENT }}
-          flavor: |
-            latest=false
+          secrets: |
+            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
+            secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ env.DOCKER_USERNAME }}
+          password: ${{ env.DOCKER_PASSWORD }}
+      - name: Create manifest list and push
+        run: |
+          docker buildx imagetools create -t ${{ env.IMAGE }}:${{ env.TAG }} ${{ env.IMAGE }}:${{ env.TAG }}-amd64 ${{ env.IMAGE }}:${{ env.TAG }}-arm64
+      - name: Create head manifest list and push
+        run: |
+          if [[ "${{ github.ref_name }}" == release/v* ]]; then
+            docker buildx imagetools create -t ${{ env.IMAGE }}:${{ env.HEAD_TAG }} ${{ env.IMAGE }}:${{ env.TAG }}-amd64 ${{ env.IMAGE }}:${{ env.TAG }}-arm64
+          fi
+      - name: Inspect image
+        run: |
+          docker buildx imagetools inspect ${{ env.IMAGE }}:${{ env.TAG }}
+  merge-agent-manifest:
+    runs-on: ubuntu-latest
+    needs: [push-images, build-agent-windows]
+    permissions:
+      contents: read
+      id-token: write
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      - name: Setup Environment Variables
+        uses: ./.github/actions/setup-tag-env
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
       - name: Load Secrets from Vault
         uses: rancher-eio/read-vault-secrets@main
         with:
